---

- hosts: multi
  roles:
  - virtualmin
  - fullstack-system-packages

- hosts: prod
  roles:
  - { role: virtualmin-virtual-server, virtualmin_user: prod }
  - { role: geerlingguy.redis, when: install_redis }

- hosts: stage
  roles:
  - { role: geerlingguy.redis, when: install_redis }

- hosts: dev
  roles:
  - { role: geerlingguy.redis, when: install_redis }
