---

- hosts: multi
  roles:
  - virtualmin
  - fullstack-system-packages

- hosts: prod
  roles:
  - { role: virtualmin-virtual-server, virtualmin_user: prod }

- hosts: stage
  roles:
  - { role: virtualmin-virtual-server, virtualmin_user: stage }

- hosts: dev
  roles:
  - { role: virtualmin-virtual-server, virtualmin_user: dev }
