# Settings and variables

# Ubuntu version
ubuntu_version_name: ubuntu-xenial

# How many chars to use when creating passwords
password_chars: 24

# Drush version to checkout
drush_version: 8.1.0

# Blank out user passwords from /root/passwords once fetched to local
remove_user_passwords: yes

install_docker: yes

# Solr requires docker to be installed
# (will skip if install_docker is set to no)
install_solr: yes

install_redis: yes

# Optional system packages.
# To disable change install to no and run setup.yml playbook
packages:

# PHP 5 specific
- package: "php5-redis"
  install: no
- package: "php5-curl"
  install: no

# PHP 7 specific
- package: "php-redis"
  install: yes
- package: "php-curl"
  install: yes

- package: "imagemagick"
  install: yes
- package: "default-jre"
  install: yes

environments:
  prod:
    name: Production
    redis_db: 1
    color: "#c00"
    # Don't set remote_envs for prod so it remains isolated
    # I.e. There are no drush sync scripts required upsteam to prod
    remote_envs:
  stage:
    name: Staging
    redis_db: 2
    color: "#00c"
    remote_envs:
      - dev
      - prod
  dev:
    name: Development
    redis_db: 3
    color: "#0c0"
    remote_envs:
      - stage
      - prod

php:
  memory_limit: 2048M
  upload_size: 100M
  timeout: 900
