---

- name: Install virtualmin.
  script: >
    ./roles/virtualmin/scripts/virtualmin-install.sh -y
    creates=/etc/webmin/miniserv.conf

- name: Install root SSL certificate.
  script: >
     ./roles/virtualmin/scripts/create_self_signed_certificate_root.sh
     creates=/root/ssl/root.crt

- name: CHECK if webmin config is already updated from the standard
  shell: grep 'port=12340' {{ webmin_path }}/miniserv.conf
  register: miniserv_conf
  changed_when: "miniserv_conf.rc != 0"

- name: Copy miniserv.conf
  template:
    src: "miniserv.conf"
    dest: "{{ webmin_path }}/miniserv.conf"
  changed_when: "miniserv_conf.rc != 0"
  notify: restart webmin

#- name: CHECK if webmin version has been set
#  command: grep MiniServ /etc/webmin/miniserv.conf
#  register: webmin_version_set
#  changed_when: false
#  ignore_errors: yes

- name: GET webmin version
  shell: cat /etc/webmin/webmin/config | grep last_version_number | cut -d "=" -f2
  register: webmin_version
  changed_when: false

- name: Set miniserv.conf webmin version
  #script: ./roles/virtualmin/scripts/set_webmin_version.sh
  #changed_when: "webmin_version_set.rc != 0"
  lineinfile: >
    dest=/etc/webmin/miniserv.conf
    regexp='^server=MiniServ'
    line='server=MiniServ/{{ webmin_version.stdout }}'
    create=yes
    backrefs=yes
    state=present
  #changed_when: "webmin_version_set.rc == 0"

- name: Set bash as default shell
  lineinfile: >
    dest=/etc/webmin/virtual-server/config
    regexp=^unix_shell=
    line=unix_shell=/bin/bash

- name: CHECK if virtualmin features are already disabled
  shell: grep '^plugins=virtualmin-htpasswd$' /etc/webmin/virtual-server/config
  register: virtual_modules_disabled
  changed_when: "virtual_modules_disabled.rc != 0"

- name: Disable awstats, webalizer, mailman
  script: ./roles/virtualmin/scripts/disable_virtualmin_features.sh
  changed_when: "virtual_modules_disabled.rc != 0"

- name: Start the webmin service.
  service:
    name: webmin
    state: started
    enabled: yes
