---

- name: Set hostname
  hostname: name="{{ hostname }}"

- name: Install virtualmin.
  script: >
    ../scripts/virtualmin-install.sh -y
    creates=/etc/webmin/miniserv.conf

- name: Install root SSL certificate.
  script: >
     ../scripts/create_self_signed_certificate_root.sh
     creates=/root/ssl/root.crt

- name: CHECK if webmin config is already updated from the standard
  shell: "grep 'port=12340' {{ webmin_path }}/miniserv.conf | wc -l"
  register: miniserv_conf
  changed_when: "miniserv_conf.stdout == '0'"

- name: Copy miniserv.conf
  template:
    src: "miniserv.conf"
    dest: "{{ webmin_path }}/miniserv.conf"
  when: "miniserv_conf.stdout == '0'"
  notify: restart webmin

- name: Get webmin version
  shell: cat {{ webmin_path }}/webmin/config | grep last_version_number | cut -d "=" -f2
  register: webmin_version
  changed_when: false

- name: Set miniserv.conf webmin version
  lineinfile: >
    dest=/etc/webmin/miniserv.conf
    regexp='^server='
    line='server=MiniServ/{{ webmin_version.stdout }}'

- name: Set bash as default shell
  lineinfile: >
    dest=/etc/webmin/virtual-server/config
    regexp=^unix_shell=
    line=unix_shell=/bin/bash

- name: Disable awstats, webalizer, mailman
  lineinfile: >
      dest=/etc/webmin/virtual-server/config
      regexp=^plugins=.*
      line=plugins=virtualmin-htpasswd

- name: Disable apache's default virtualhost
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify:
    - reload apache2

- name: Start the webmin service.
  service:
    name: webmin
    state: started
    enabled: yes
