---

# Install drush helper scripts for all environments except prod

- name: Create ~/.drush directory
  file: path=~/.drush state=directory
  become: yes
  become_user: "{{ user }}"
  when: user != 'prod'

- name: Create ~/.drush/scripts directory
  file: path=~/.drush/scripts state=directory
  become: yes
  become_user: "{{ user }}"
  when: user != 'prod'

- name: Create ~/.drush/drush_bashrc file
  template: src=../templates/drush_bashrc dest=~/.drush/drush_bashrc
  become: yes
  become_user: "{{ user }}"
  when: user != 'prod'

- name: Create ~/.drush/scripts/* files
  template: src=../templates/drush_pull_script dest=~/.drush/scripts/{{ item }}
  with_items: "{{ environments[user].remote_envs }}"
  become: yes
  become_user: "{{ user }}"
  when: user != 'prod'

# Install Drupal

- name: Add git repository for project
  git: accept_hostkey=True
       repo={{ project_repo }}
       dest=/home/"{{ user }}"/git
       version=master
  become: yes
  become_user: "{{ user }}"

- name: Check if public_html is a link
  stat: path=/home/{{ user }}/public_html
  register: sym

- name: Remove public_html as a directory
  file: path=/home/{{ user }}/public_html state=absent force=true
  when: sym.stat.islnk is defined and sym.stat.islnk == False

- name: Remove public_html directory and replace with a link to git/www
  file: src=/home/{{ user }}/git/www dest=/home/{{ user }}/public_html state=link force=true
  when: sym.stat.islnk is defined and sym.stat.islnk == False

- name: Copy site/default/local.settings.php file
  template: src=local.settings.php dest="/home/{{ user }}/git/www/sites/default/local.settings.php" mode="u=r,g=r,o="
  become: yes
  become_user: "{{ user }}"

- name: Copy database ready for import
  copy: src=deploy/db.sql.gz dest=/tmp/db.sql.gz force=no mode="u=rwx,g=rwx,o=rwx"

- name: Gunzip the sql.gz database
  shell: "gunzip -fk /tmp/db.sql.gz"
  args:
    creates: /tmp/db.sql

- name: Check if {{ user }} database already has tables
  shell: "echo 'use {{ user }}; show tables' | mysql -u {{ user }} -p{{ lookup('file', 'fetched/' + hostname + '/passwords/' + user) }} {{ user }} | wc -l"
  register: dbstatus
  changed_when: dbstatus.stdout | int <= 1

- name: Import database to {{ user }} database - once only
  mysql_db: name="{{ user }}" state=import target=/tmp/db.sql login_user="{{ user }}" login_password="{{ lookup("file", "fetched/" + hostname + "/passwords/" + user) }}"
  become: yes
  become_user: "{{ user }}"
  when: dbstatus.stdout | int <= 1

- name: Copy Drupal files directory gzip tarball ready for extraction
  copy: src=deploy/files.tar.gz dest=/tmp/files.tar.gz force=no mode="u=rwx,g=rwx,o=rwx"

- name: Extract Drupal files
  shell: 'tar xzf /tmp/files.tar.gz -C /home/{{ user }}/git/www/sites/default && chown -R {{ user }}:{{ user }} /home/{{ user }}/git/www/sites/default/files'
  args:
    creates: "/home/{{ user }}/git/www/sites/default/files/.htaccess"