---

- name: Create ~/.drush directory
  file: path=~/.drush state=directory
  become: yes
  become_user: "{{ user }}"
  when: user != 'prod'

- name: Create ~/.drush/scripts directory
  file: path=~/.drush/scripts state=directory
  become: yes
  become_user: "{{ user }}"
  when: user != 'prod'

- name: Create ~/.drush/drush_bashrc file
  template: src=../templates/drush_bashrc dest=~/.drush/drush_bashrc
  become: yes
  become_user: "{{ user }}"
  when: user != 'prod'

- name: Create ~/.drush/scripts/* files
  template: src=../templates/drush_pull_script dest=~/.drush/scripts/{{ item }}
  with_items: "{{ environments[user].remote_envs }}"
  become: yes
  become_user: "{{ user }}"
  when: user != 'prod'